### ISSUE TITLE
Mongo Database Server

### ISSUE THREAD

**Issue by GaryFrewin** [Rothamsted-Ecoinformatics/DatasetKPIs#1]
An issue which contains an overview of the MongoDB persistance Layer of the DatasetKPI project

#### Description
To design and implement a MongoDB database into which the Python later will load data. The MongoDB flexible schema will 

#### Files
Architecture Outline (MIRO board) https://miro.com/app/board/uXjVOsq856Y=/

#### Tasks
- [ ] Send DB specification to Constantin to set up the server
- [ ] Create configuration file with Logging path, etc etc
- [ ] Define Document Schema using CreateCollection() with appropriate validator settings
- [ ] Configure logging tables
