### ISSUE TITLE
Python Backend Layer

### ISSUE THREAD

**Issue by GaryFrewin** [Rothamsted-Ecoinformatics/DatasetKPIs#2]
An issue which contains an overview of the Python Layer of the DatasetKPI project

#### Description
To build a Python Program capable of loading data from various sources (APIs, SQL, Scraping, CSVs), transforming it and loading it into a MongoDBDatabase where it will be queried. As there will be numerous datasources which need integrating into the MongoDB schema, the design pattern for dealing with this variety should be carefully thought through so that it is easy to add new data sources. Consider Adapter patterns and Repository patterns, facilitating an ETL type pipeline. 

#### Files
Architecture Outline (MIRO board) https://miro.com/app/board/uXjVOsq856Y=/

#### Tasks
- [x] Create  a basic script that can connect to MongoDB Server
- [ ] Extend Script to call API, retrieve data and transform, insert into collection using document schema
- [ ] Design pattern choice for extending the script to include multiple data sources and types
- [ ] Implement required classes for each datasource... probably work on one new data source at a time.
